org: continuousaardwolf
app: mondayautov1
service: mondayautov1
frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  region: us-east-2
  runtime: nodejs18.x

plugins:
  - serverless-layers

custom:
  serverless-layers:
    - mondayautov1-node-modules:
        dependenciesPath: ./package.json
        layersDeploymentBucket: mondayautov1-bucket
    - AWS-Parameters-and-Secrets-Lambda-Extension:
        arn: arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
        layersDeploymentBucket: mondayautov1-bucket

functions:
  mondayautov1:
    handler: index.handler
    url:
      cors: true
    timeout: 15
