org: continuousaardwolf
app: hubspottomondayv1
service: hubspottomondayv1
frameworkVersion: "3"

provider:
  name: aws
  region: us-east-2
  runtime: nodejs18.x

plugins:
  - serverless-layers

custom:
  serverless-layers:
    - hubspottomondayv1-node-modules:
        dependenciesPath: ./package.json
        layersDeploymentBucket: hubspottomondayv1-bucket
    - AWS-Parameters-and-Secrets-Lambda-Extension:
        arn: arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
        layersDeploymentBucket: hubspottomondayv1-bucket

functions:
  hubspottomondayv1:
    handler: index.handler
    url:
      cors: true
    timeout: 15
